### ISSUE TITLE
Can not find neurolots

### ISSUE THREAD

**Issue by wuhanhui** [vg-lab/NeuroTessMesh#2]
I have downloaded neurolots and compiled it myself but how can I link it in this project with cmake. The error is like as follow,

CMake Error at CMake/common/CommonFindPackage.cmake:102 (message):
  Not configured neurotessmesh: Required neurolots not found
Call Stack (most recent call first):
  CMakeLists.txt:52 (common_find_package)

**Comment by juanjosegarcan** [comment]
Hi, 
I will fix the repository to get neurolots dependency directly from github repository. But anyway, if you prefer I can send you the application precompiled!

**Comment by wuhanhui** [comment]
Thanks. I am running on Ubuntu 16 or Windows 10. And Can you send me either of the precompiled application to my email 
whhfly2003@gmail.com. 
By the way, If you fix the repository, I can have a test for you both on windows and ubuntu. I think this repository is not updated like your gitlab repository.

**Comment by juanjosegarcan** [comment]
The denpendecy issue is already fixed, all dependencies are updated to github repositories.
 This is the link to the precompiled apps: http://gmrv.es/gmrvvis/apps/neurotessmesh/0.0.1/  
Thanks so much for your feedback

**Comment by wuhanhui** [comment]
I have downloaded the app. It works on window 10 but missing the glew32.dll. I copy it from my cuda packages. So I think you can fix the apps with including the glew32.dll in the zip. But I still have some questions
1. I run the app and read the source code but I found no neuron smoothing methods but from the screenshot from [neuroTessMesh](http://gmrv.es/neurotessmesh/neuroTessMesh.jpg ) there should be a function like that. So I think maybe this repo from github is not up to date.
2. The readme.md of this repo should be updated as the tutorial of the building step is
git clone https://gitlab.gmrv.es/nsviz/NeuroTessMesh.git
3. In CMakeLists.txt there is a line to require neurolots  like this below
 common_find_package(neurolots REQUIRED)
But I can not find a find method to find neuronlots  in cmake. Meanwhile, I can not find any including dependencies of neuronlots in the source code.

Thanks for your reply

**Comment by juanjosegarcan** [comment]
1. You are right, there is an incoherence between the application and the user guide, but it's the guide that isn't updated. The functionality that you mention is not available in the newest version of the application. Sorry for the inconvenience, I have to update the user guide.You are right, there is an incoherence between the application and the user guide, but it's the guide that isn't updated. The functionality that you mention is not available in the newest version of the application. Sorry for the inconvenience, I have to update the user guide
2. You are right about this too, I will fix this as soon as possible.  
3. There are two different things in this respect. The first one is that the find to neurolots is being doing in the call common_find_package(neurolots REQUIRED), we are using an abstraction of cmake call cmake common that facilitates part of the work of cmake libraries management. And the second one neurolots is composed of severeal libraries (nlgeometry, nlgenerator, nlrender, nlphysics), are those that are included in the source code.  

Again, thanks so much for your feedback.

**Comment by wuhanhui** [comment]
OK, thanks for you and your group's great project about neuron mesh. I am very interested in that. I will try to compile it later to check if there are other problems

**Comment by wuhanhui** [comment]
It works on Ubuntu 16 with these modified commands
`git submodule update --init `
` cmake .. -DCLONE_SUBPROJECTS=ON -DCMAKE_BUILD_TYPE=Release `

Thanks
